name: My First GitHub Action
run-name: ${{ github.actor }} is testing GitHub Actions
on: [ push, workflow_call ]
jobs:
  job_1:
    name: "Bootstrap Greeting"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Пайплайн запущен 🚀"
      - run: echo "Удачного прохождения!"
  
  job_2:
    name: "Compile And Run"
    needs: job_1
    runs-on: ubuntu-latest
    container: openjdk:21
    steps:
      - uses: actions/checkout@v3
      - run: javac src/app/Main.java
      - run: java src/app/Main
  
  job_3:
    name: "The End"
    needs: job_2
    runs-on: ubuntu-latest
    steps:
      - run: echo "Пайплайн успешно завершен, всего хорошего 🤝"
    

